// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpendLess.Infrastructure;

#nullable disable

namespace SpendLess.Infrastructure.Migrations
{
    [DbContext(typeof(SpendLessContext))]
    partial class SpendLessContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SpendLess.Infrastructure.Models.DbCategory", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("432ad70b-8ef5-407d-b375-2bd185426de8"),
                            Name = "Rachunki"
                        },
                        new
                        {
                            CategoryId = new Guid("970d8398-765b-44d2-aef8-9205a6b43ef6"),
                            Name = "Wydatki stałe"
                        },
                        new
                        {
                            CategoryId = new Guid("8aa3dcc6-6e03-43f6-b6b0-83ad31e343f9"),
                            Name = "Zdrowie"
                        },
                        new
                        {
                            CategoryId = new Guid("f937ad10-43fe-41fa-a899-2c6db467ef61"),
                            Name = "Transport/Paliwo"
                        });
                });

            modelBuilder.Entity("SpendLess.Infrastructure.Models.DbExpense", b =>
                {
                    b.Property<Guid>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ExpenseDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExpenseId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Expenses", (string)null);
                });

            modelBuilder.Entity("SpendLess.Infrastructure.Models.DbExpense", b =>
                {
                    b.HasOne("SpendLess.Infrastructure.Models.DbCategory", "Category")
                        .WithMany("Expenses")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SpendLess.Infrastructure.Models.DbCategory", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
